services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  parser:
    build: .
    command: python parser.py

  handler:
    build: .
    command: python job_handler.py
    depends_on:
      - redis
      - parser

  worker:
    build: .
    command: python worker.py
    depends_on:
      - redis
