[project]
name = "queue-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "msgraph-sdk>=1.28.0",
    "pymongo>=4.12.1",
    "redis>=6.0.0",
    "rq>=2.3.2",
]
